import { useState, useMemo } from 'react';
import PositionChart from '../components/PositionChart';
import CdfChart from '../components/CdfChart';
import LambdaChart from '../components/LambdaChart';
import PointsDecomposition from '../components/PointsDecomposition';
import ScoringTable from '../components/ScoringTable';
import { simulateRaces, computeExpectedPoints } from '../lib/simulation';
import './Methodology.css';

export default function Methodology({ data }) {
  const [selectedIdx, setSelectedIdx] = useState(0);
  const driver = data.drivers[selectedIdx];
  const teamColor = data.teams[driver.team_idx].color;

  // Run client-side simulation for the interactive distribution
  const simDistribution = useMemo(() => {
    const logLambdas = data.drivers.map(d => d.lambda);
    const pDnfs = data.drivers.map(d => d.p_dnf);
    const result = simulateRaces(logLambdas, pDnfs, 15000, 123);
    return result;
  }, [data.drivers]);

  const driverDist = simDistribution[selectedIdx];

  return (
    <div className="methodology">
      <header className="meth-header">
        <h1>How It Works</h1>
        <p className="meth-subtitle">
          From betting odds to expected fantasy points, in four steps.
        </p>
      </header>

      {/* Driver selector */}
      <div className="driver-selector">
        <label htmlFor="driver-select">Explore driver</label>
        <select
          id="driver-select"
          value={selectedIdx}
          onChange={e => setSelectedIdx(Number(e.target.value))}
        >
          {data.drivers.map((d, i) => (
            <option key={d.abbr} value={i}>{d.name} ({d.abbr})</option>
          ))}
        </select>
      </div>

      {/* Step 1 */}
      <section className="meth-section">
        <div className="step-num">1</div>
        <h2>Convert Odds to Fair Probabilities</h2>
        <p>
          Bookmaker odds embed a margin (the "vig"). A +200 line doesn't mean 33% — it means
          something less, once you account for the bookmaker's edge. We use <strong>Shin's method</strong> to
          remove the vig. Unlike simple normalization, Shin's method corrects for the
          favorite-longshot bias: bookmakers systematically underprice favorites and overprice
          longshots. The method solves for an "insider trading" parameter z, then backs out
          fair probabilities. The result: probabilities that sum to exactly 1.0, with the bias removed.
        </p>
        <p>
          We pull odds from The Odds API (race winner market) and supplement with manual odds
          from Oddschecker for podium, top 6, top 10, and DNF markets when available. More
          markets = tighter constraints on the model.
        </p>
      </section>

      {/* Step 2 */}
      <section className="meth-section">
        <div className="step-num">2</div>
        <h2>Fit the Plackett-Luce Model</h2>
        <p>
          The Plackett-Luce model assigns each driver a strength parameter <strong>λ</strong>.
          The probability that driver i wins from a remaining set S is simply λ_i / Σλ_j.
          A full finishing order is generated by drawing winners sequentially: pick the winner
          from all drivers, then pick 2nd from the remaining set, and so on.
        </p>
        <p>
          We decompose strength as <code>log(λ) = μ_team + δ_driver</code>, so teammates share
          a team component. This creates natural positive correlation — if one Mercedes is strong,
          both are. The optimizer fits λ values by minimizing the squared error between the model's
          implied probabilities and the devigged odds. Each evaluation runs ~20K simulations,
          and the optimizer takes ~200 evaluations to converge.
        </p>

        <h3>Driver Strength (λ)</h3>
        <p className="muted" style={{ marginBottom: 8 }}>
          Click a driver to explore their distribution below. Teammates are connected.
        </p>
        <LambdaChart
          drivers={data.drivers}
          teams={data.teams}
          selectedIdx={selectedIdx}
          onSelect={setSelectedIdx}
        />
      </section>

      {/* Step 3 */}
      <section className="meth-section">
        <div className="step-num">3</div>
        <h2>Simulate {data.meta.n_simulations.toLocaleString()} Races</h2>
        <p>
          With the fitted λ values and DNF probabilities, we simulate {data.meta.n_simulations.toLocaleString()} complete
          races. In each simulation: first, each driver independently rolls for DNF (based on
          team reliability + driver risk). Then the Plackett-Luce model draws a finishing order
          for all non-DNF drivers. The result is a full probability distribution over all 23
          outcomes (P1 through P22, plus DNF) for every driver.
        </p>

        <h3>Position Distribution — {driver.name}</h3>
        <p className="muted" style={{ marginBottom: 8 }}>
          Hover bars for exact probabilities. Red bar = DNF.
          (Interactive: re-simulated with 15K races in your browser.)
        </p>
        <PositionChart
          distribution={driverDist}
          color={teamColor}
          scoring={data.scoring.race}
        />

        <h3 style={{ marginTop: 24 }}>Cumulative Distribution</h3>
        <p className="muted" style={{ marginBottom: 8 }}>
          Dots show the market cutoff points used for fitting.
        </p>
        <CdfChart distribution={driverDist} color={teamColor} />
      </section>

      {/* Step 4 */}
      <section className="meth-section">
        <div className="step-num">4</div>
        <h2>Compute Expected Points</h2>
        <p>
          Expected points = Σ P(position k) × points(k) + P(DNF) × (-20). Each finishing
          position contributes its probability times its point value. The DNF penalty of -20 is
          a significant drag — drivers with high DNF risk (12%+) can have negative expected points
          even if they occasionally finish in the top 10.
        </p>

        <h3>Points Decomposition — {driver.name}</h3>
        <p className="muted" style={{ marginBottom: 8 }}>
          How much each finishing position contributes to expected points.
        </p>
        <PointsDecomposition
          distribution={driver.position_distribution}
          scoring={data.scoring.race}
          dnfPenalty={data.scoring.dnf_penalty}
          color={teamColor}
        />
      </section>

      {/* Scoring reference */}
      <section className="meth-section">
        <h2>Scoring Rules</h2>
        <p style={{ marginBottom: 12 }}>
          Our family league scoring. Each player picks 5 drivers before qualifying each weekend.
          No budget cap, no qualifying points, no fastest lap.
        </p>
        <ScoringTable scoring={data.scoring} />
      </section>
    </div>
  );
}
